# Generated by Django 5.0.9 on 2026-08-05 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('ambulance_type', models.CharField(choices=[('basic', 'Basic Life Support'), ('advanced', 'Advanced Life Support'), ('neonatal', 'Neonatal'), ('air', 'Air Ambulance')], default='basic', max_length=20)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_phone', models.CharField(max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('en_route', 'En Route'), ('at_scene', 'At Scene'), ('transporting', 'Transporting'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ambulances',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('medical', 'Medical Emergency'), ('accident', 'Accident'), ('cardiac', 'Cardiac Arrest'), ('fire', 'Fire'), ('other', 'Other')], default='ambulance', max_length=20)),
                ('patient_condition', models.TextField(blank=True)),
                ('pickup_address', models.TextField(blank=True)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('no_resource', 'No Resource Available')], default='pending', max_length=20)),
                ('estimated_arrival_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='ambulance.ambulance')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ambulance',
            index=models.Index(fields=['status', 'is_active'], name='ambulances_status_af5aa4_idx'),
        ),
    ]
