# Generated by Django 5.0.9 on 2026-08-05 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, max_length=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('last_donated_at', models.DateField(blank=True, null=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_donors',
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_needed', models.PositiveIntegerField(default=1)),
                ('units_fulfilled', models.PositiveIntegerField(default=0)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('patient_name', models.CharField(max_length=150)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=25)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blood_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donated_at', models.DateField(auto_now_add=True)),
                ('volume_ml', models.PositiveIntegerField(default=450)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='blood.blooddonor')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blood.bloodrequest')),
            ],
            options={
                'db_table': 'donation_history',
                'ordering': ['-donated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blooddonor',
            index=models.Index(fields=['blood_group', 'is_available'], name='blood_donor_blood_g_32f8db_idx'),
        ),
    ]
