# Generated by Django 5.0.9 on 2026-08-05 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('office_type', models.CharField(choices=[('municipality', 'Municipality'), ('district', 'District Office'), ('ministry', 'Ministry'), ('court', 'Court'), ('police', 'Police Station'), ('tax', 'Tax Office'), ('immigration', 'Immigration'), ('land', 'Land Registry'), ('other', 'Other')], default='other', max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('office_hours', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'government_offices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_documents', models.JSONField(default=list)),
                ('processing_time', models.CharField(blank=True, max_length=100)),
                ('fee', models.CharField(blank=True, max_length=100)),
                ('application_url', models.URLField(blank=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='government.governmentoffice')),
            ],
            options={
                'db_table': 'government_services',
            },
        ),
    ]
