# Generated by Django 5.0.9 on 2026-09-24 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_smart_health_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-average_rating', 'full_name']},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['-average_rating', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='hospital',
            name='hospitals_emergen_49f1fb_idx',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'status'], name='appointment_hospita_ab3622_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['hospital', 'status'], name='hospital_de_hospita_f6e104_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='hospital_de_name_7c198e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['full_name'], name='doctors_full_na_f9e005_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active', 'is_verified'], name='doctors_is_acti_d2e13d_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorhospital',
            index=models.Index(fields=['doctor', 'hospital'], name='doctor_hosp_doctor__a0f06b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorhospital',
            index=models.Index(fields=['hospital', 'department'], name='doctor_hosp_hospita_464687_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorleave',
            index=models.Index(fields=['doctor', 'status', 'start_date', 'end_date'], name='doctor_leav_doctor__f6a4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['doctor', 'day_of_week', 'status'], name='doctor_sche_doctor__8020ba_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['hospital', 'branch'], name='doctor_sche_hospita_fcfabf_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['emergency_available', 'hospital_type'], name='hospitals_emergen_b52aab_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city', 'area'], name='hospitals_city_59c411_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['status', 'is_verified'], name='hospitals_status_8b4196_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbranch',
            index=models.Index(fields=['hospital', 'status'], name='hospital_br_hospita_a1b433_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbranch',
            index=models.Index(fields=['city', 'area'], name='hospital_br_city_03f9f0_idx'),
        ),
    ]
