# Generated by Django 5.0.9 on 2026-08-05 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('madrasa', 'Madrasa'), ('technical', 'Technical Institute'), ('coaching', 'Coaching Center')], max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('admission_open', models.BooleanField(default=False)),
                ('admission_deadline', models.DateField(blank=True, null=True)),
                ('admission_info_url', models.URLField(blank=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'institutions',
                'ordering': ['-average_rating'],
            },
        ),
    ]
